base/urls.py
from django.urls import path, include

from rest_framework import routers

from base import views

app_name = 'base'
urlpatterns = [

]

front/urls.py
from django.urls import path, include

from rest_framework import routers

from front import views

app_name = 'front'
urlpatterns = [
    path('acerca/', views.acerca, name='acerca'),
    path('search/', views.search, name='search'),
    path('trend/<str:hashtag>', views.trend, name='trend'),
    path('', views.index, name='index'),
    path('<str:location>/', views.index, name='index'),
    path('<str:location>/<str:when>/', views.index, name='index'),
    path('<str:location>/<str:when>/<int:hour>/', views.index, name='index'),
    
    #path('stats/<str:hashtag>/<str:location>/<str:date>/<int:hour>/', views.trend_stats, name='trend_stats'),
]

trendsweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
    path('', include('front.urls')),
    path('', include('base.urls')),
]

base/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Trends(models.Model):
    location = models.CharField(max_length=50)
    hashtag = models.CharField(max_length=100)
    tweets_counter = models.IntegerField()
    position = models.IntegerField()
    trend_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'trends'

front/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render

# Create your views here.

front/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.db.models.functions import Lower

from django_pandas.io import read_frame

from base.models import Trends

from front.utils import change_col_name, get_globales

from utils.vars import places

from urllib.parse import unquote

import pandas as pd
import numpy as np
import datetime
import arrow

def index(request, location='Peru', when='', hour=-1):
    # Obteniendo data del location.
    try:
        location_data = next(item for item in places() if item['key'] == location)
    except:
        HttpResponseRedirect(reverse('front:index'))

    # Obteniendo data UTC.
    if when == '':
        utcnow = arrow.utcnow()
        utcprev = utcnow.shift(hours=-1)
    else:
        if hour == -1:
            utcnow = arrow.get(when, 'YYYY-MM-DD')
            utcprev = utcnow.shift(hours=-1)
        else:
            utcnow = arrow.get('%s %s:0:0' % (when, hour+1), 'YYYY-MM-DD H:m:s')
            utcprev = utcnow.shift(hours=-1)

    fecha = utcnow
    if hour == -1:
        utcnow = utcnow.shift(hours=location_data['shift'])
        utcprev = utcprev.shift(hours=location_data['shift'])


    trends = Trends.objects.filter(
        location=location,
        trend_date__range=[utcprev.datetime, utcnow.datetime]
    )
    print(trends.query)

    df = read_frame(trends)
    #df.to_csv('trends.csv')

    pv = pd.pivot_table(df, index='hashtag', values=['position', 'tweets_counter'],
        aggfunc={'position': np.average, 'tweets_counter': max})
    
    newdf = pd.DataFrame(pv.to_records())

    try:
        newdf = newdf.sort_values(by=['position'])
    except:
        pass
    newdf = newdf.to_dict('records')

    horas = list(range(0,23))

    q = request.GET.get('q', '')

    context = {
        'newdf': newdf,
        'location': location,
        'when': when,
        'fecha': arrow.get(fecha).datetime,
        'places': places(),
        'hour': hour,
        'location_data': location_data,
        'horas': horas,
        'q': q
    }
    return render(request, 'front/index.html', context)

def search(request):
    q = request.GET.get('q', '')
    q = q.strip()

    trends = Trends.objects.filter(hashtag__icontains=q)

    df = read_frame(trends)
    df['trend_date'] = df['trend_date'].map(lambda f: arrow.get(f).date())

    pv = pd.pivot_table(df, index=['hashtag', 'location'], values='tweets_counter',
        aggfunc=[np.average, 'count'])
    newdf = pd.DataFrame(pv.to_records())
    newdf.reset_index()
    newdf.fillna(0)
    new_cols = newdf.columns.values
    new_cols = [change_col_name(a) for a in new_cols]
    newdf.columns = new_cols
    #newdf.to_csv('test.csv', index=False)

    context = {
        'newdf': newdf.to_dict('records'),
        'q': q
    }
    return render(request, 'front/search.html', context)

def trend(request, hashtag):
    q = request.GET.get('q', '')

    trends = Trends.objects.filter(hashtag=hashtag)
    df = read_frame(trends)
    first = df['hashtag'][0]
    df['trend_date'] = df['trend_date'].map(lambda f: arrow.get(f).date())
    df['hashtag'] = df['hashtag'].map(lambda h: first)
    pv = pd.pivot_table(df, index=['hashtag', 'location'], columns='trend_date', values='tweets_counter', aggfunc=np.average)

    newdf = pd.DataFrame(pv.to_records())
    newdf.reset_index()
    newdf.fillna(0)

    globales = get_globales()

    context = {
        'globales': globales,
        'hashtag': hashtag,
        'newdf': newdf.to_dict('records'),
        'q': q
    }

    newdf.to_csv('hashtag.csv', index=False)
    return render(request, 'front/trend.html', context)


def acerca(request):
    
    return render(request, 'front/acerca.html')

front/templates/front/acerca.html
{% extends 'front/base.html' %}

{% block content %}
    <div class="container">
        <div class="acerca bg-white rounded border p-3">
            <h1>Acerca de Twitnd</h1>
            <h3>¿Qué es Twitnd?</h3>
            <p>
                Twitnd es un colector de tendencias en algunos paises de habla hispana.
            </p>
            <h3>¿De dónde obtiene las tendencias?</h3>
            <p>
                Twitnd obtiene datos desde la aplicación Tweetdeck de Twitter.
            </p>
            <h3>¿Cómo obtiene los datos?</h3>
            <p>
                Twitnd tiene un <a href="https://github.com/soncco/trends-scraper">algoritmo de scraping</a>, el cual revisa Tweetdeck cada 15 minutos y colecta tendencias con los siguientes datos:
            </p>
            <ul>
                <li>El hashtag o tendencia.</li>
                <li>La ubicación de la tendencia, por ejemplo: "Perú".</li>
                <li>La posición en la que se muestra.</li>
                <li>La cantidad de Tweets.</li>
                <li>La fecha y hora de la recolección de acuerdo al timezone de la ubicación, por ejemplo en Perú sería UTC-5.</li>
            </ul>
            <h3>¿Desde cuándo?</h3>
            <p>
                Las tendencias han sido almacenadas desde el 16 de Julio del 2020 a las 11:30 horas UTC-5.
            </p>
            <h3>¿Por qué?</h3>
            <p>
                Como parte de una investigación para la <a href="https://www.researchgate.net/publication/339365342_Fake_News_in_Spanish_Towards_the_building_of_a_Corpus_based_on_Twitter">creación de corpus para detección de Fake News en español</a>, esta herramienta permitirá obtener tweets con URLs, con estas URLs se crearán datasets que permitan entrenar modelos que permitan detectar
                Fake News en idioma español.
            </p>

            <h3>¿Puedo ayudar?</h3>
            <p>
                Puedes ayudar contribuyendo en <a href="https://github.com/soncco/trends-scraper">el código fuente del scraper</a>, o también puedes apoyarnos con los gastos operativos del sitio medianta PayPal.
            </p>
            <p class="text-center">
                <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                    <input type="hidden" name="cmd" value="_s-xclick" />
                    <input type="hidden" name="hosted_button_id" value="N6HQZC75BL844" />
                    <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
                    <img alt="" border="0" src="https://www.paypal.com/en_PE/i/scr/pixel.gif" width="1" height="1" />
                </form>                    
            </p>
        </div>
    </div>    
{% endblock content %}


{% block title %}Acerca de Twitnd{% endblock title %}
    

front/templates/front/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/redmond/jquery-ui.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'front/css/trends.css' %}">
    {% block js_head %}
    {% endblock js_head %}
    <title>{% block title %}{% endblock %} - Tendencias de Twitter en español - Twitnd</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light mb-4" style="background-color: #fff;">
        <a class="navbar-brand" href="{% url 'front:index' %}">Twitnd <span class="text-muted">β</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'front:acerca' %}">Acerca</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'front:search' %}">
                <input class="form-control mr-sm-2" type="search" name="q" value="{{q}}">
                <button class="btn btn-primary my-2 my-sm-0" type="submit">Buscar</button>
            </form>
        </div>
    </nav>

    {% block content %}
    {% endblock content %}

    <footer>
        <div class="container">
            <div class="trends-settings bg-white rounded border p-3 mt-2 mb-2">
                <p class="text-right text-muted">
                    <a href="https://github.com/soncco/trends-scraper/blob/master/LICENSE">Apache License 2.0</a>. Contacto: 992182@unsaac.edu.pe <br>
                    Hecho sólo con fines educativos
                </p>
            </div>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    <script src="{% static 'front/js/dp.es.js' %}"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-8521364-23"></script>
        <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-8521364-23');
        </script>

    {% block js %}
    {% endblock js %}
</body>
</html>

front/templates/front/index.html
{% extends 'front/base.html' %}
{% load mis_tags %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="trends-container bg-white rounded border p-3">
                    <h2>Tendencias de {{ location_data.nombre }} <span class="text-muted">({{ location_data.tz }})</span></h2>
                    <ol class="trend-list">
                    {% for trend in newdf %}
                        <li>
                            <div class="trend-info">
                                <a class="hashtag" href="{% url 'front:trend' trend.hashtag %}">{{ trend.hashtag }}</a>
                                <br>
                                {% if trend.tweets_counter > 0 %}
                                <small class="text-muted">{{ trend.tweets_counter }} tweets</small> <br>
                                {% else %}
                                <small class="text-muted">Empezando la tendencia</small> <br>
                                {% endif %}
                            </div>
                            <div class="trend-links">
                                <a href="https://twitter.com/search?q={{ trend.hashtag|clean_hashtag }}" target="_blank"><i class="fab fa-twitter    "></i> Ver en Twitter</a>
                            </div>
                        </li>
                    {% endfor %}
                    </ol>
                </div>
            </div>
            <div class="col-md-4">
                <div class="trends-settings bg-white rounded border p-3 mb-2">
                    <h4>Lugares</h4>
                    <ul class="places list-unstyled">
                        {% for place in places %}
                            {% if when != '' %}
                                <li class="border-bottom  p-1"><a href="{% url 'front:index' place.key when %}">{{ place.nombre }}</a></li>
                            {% else %}
                                <li class="border-bottom  p-1"><a href="{% url 'front:index' place.key %}">{{ place.nombre }}</a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
                <div class="trends-settings bg-white rounded border p-3 mb-2">
                    <h4>Fecha</h4>
                    <div class="form-group">
                        <input type="text" class="form-control datepicker" value="{{ fecha|date:"d/m/Y" }}" />
                        <input type="hidden" name="when" id="when" value="{{ fecha|date:"Y-m-d"}}" />
                    </div>
                </div>
                <div class="trends-settings bg-white rounded border p-3 mb-2">
                    <h4>Hora</h4>
                    {% for hora in horas %}
                        {% if hora == hour %}
                            <a href="{% url 'front:index' location fecha|date:"Y-m-d" hora %}" class="btn btn-primary btn-hora">{{ hora }}</a>
                        {% else %}
                            <a href="{% url 'front:index' location fecha|date:"Y-m-d" hora %}" class="btn btn-light btn-hora">{{ hora }}</a>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="trends-settings bg-white rounded border p-3">
                    <h4>¿Qué es Twitnd?</h4>
                    <p>Twitnd es un colector de tendencias de Twitter en algunos paises de habla hispana. Las tendencias se obtienen de Tweetdeck.
                        Estas tendencias se obtienen cada 15 minutos y
                        se muestran agrupados de acuerdo a la posición que ocupan en la aplicación. Twitnd ha sido creado sólo para fines educativos.
                    </p>
                    <p>
                        Puedes ayudarnos contribuyendo al <a href="https://github.com/soncco/trends-scraper">código fuente</a> o ayudándonos con los costos operativos.
                    </p>
                    <p class="text-center">
                        <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                            <input type="hidden" name="cmd" value="_s-xclick" />
                            <input type="hidden" name="hosted_button_id" value="N6HQZC75BL844" />
                            <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
                            <img alt="" border="0" src="https://www.paypal.com/en_PE/i/scr/pixel.gif" width="1" height="1" />
                        </form>                    
                    </p>
                </div>
            </div>
        </div>
    </div>
        
{% endblock content %}


{% block js %}
    <script>
        $.datepicker.setDefaults( $.datepicker.regional[ "es" ] );
        $('.datepicker').datepicker({
            minDate: new Date(2020, 6, 15),
            maxDate: new Date(),
            altField: '#when',
            altFormat: 'yy-mm-dd',
            onSelect: function(d, x, y) {
                location.href = '/{{ location }}/' + $('#when').val() + '/';
            }
        })
    </script>
{% endblock js %}

{% block js_head %}

{% endblock js_head %}


{% block title %}Tendencias de {{ location_data.nombre }}{% endblock title %}
    

front/templates/front/search.html
{% extends 'front/base.html' %}
{% load mis_tags %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="trends-container bg-white rounded border p-3">
                    <h2>Resultados de búsqueda</h2>
                    <p>Se muestran {{ newdf|length }} resultados en total.</p>
                    {% for trend in newdf %}
                        <section class="trend-stat">
                            <p class="location"><i class="fas fa-map-marker-alt"></i> {{ trend.location }}</p>
                            <h4 class="hashtag"><a href="{% url 'front:trend' trend.hashtag %}">{{ trend.hashtag }}</a></h4>
                            <p class="numbers text-muted">
                                Aparece {{ trend.count }} veces
                                {% if trend.average > 0 %}
                                en promedio {{ trend.average|floatformat:"0" }} tweets.
                                {% endif %}
                            </p>
                        </section>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-4">
                
            </div>
        </div>
    </div>
        
{% endblock content %}

{% block title %}"{{ q }}" en tendencias{% endblock title %}

front/templates/front/stat.html
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
<script>

</script>

front/templates/front/trend.html
{% extends 'front/base.html' %}
{% load mis_tags %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="trends-container bg-white rounded border p-3">
                    <h2>{{ hashtag }}</h2>
                    <ol class="list-unstyled trend-stat">
                    {% for n in newdf %}
                        <li class="mb-3">
                            <p class="location"><i class="fas fa-map-marker-alt"></i> {{ n.location }}</p>
                            <canvas id="chart{{ forloop.counter0 }}"></canvas>
                        </li>
                    {% endfor %}
                    </ol>
                </div>
            </div>
            <div class="col-md-4">
                <div class="trends-settings bg-white rounded border p-3 mb-2">
                    <h4>¿Cómo interpretar el gráfico?</h4>
                    <p>
                        Twitnd sólo muestra en el gráfico las fechas donde el hashtag ha sido tendencia.
                        Se agrupa cuántas veces el hashtag ha sido tendencia en el día, se toman el número de tweets y se saca un promedio el cual se muestra en el gráfico.
                    </p>
                    <p>
                        También agrupa los términos de manera "case insensitive", es decir, "vizcarra", "Vizcarra" o "VIZCARRA" serán agrupados y se mostrarán en este gráfico.
                    </p>
                    <p>
                        En algunos casos el promedio de Tweets es 0, esto es porque Tweetdeck no muestra el número de Tweets cuando algun hashtag recién está empezando a difundirse.
                    </p>
                </div>
                <div class="trends-settings bg-white rounded border p-3 mb-2">
                    <h4>Tendencias en español ahora</h4>
                    <ol class="trend-list">
                        {% for trend in globales %}
                            <li>
                                <div class="trend-info">
                                    <a class="hashtag" href="{% url 'front:trend' trend.hashtag %}">{{ trend.hashtag }}</a>
                                    <br>
                                    {% if trend.tweets_counter > 0 %}
                                    <small class="text-muted">{{ trend.tweets_counter }} tweets</small> <br>
                                    {% else %}
                                    <small class="text-muted">Empezando la tendencia</small> <br>
                                    {% endif %}
                                </div>
                                <div class="trend-links">
                                    <a href="https://twitter.com/search?q={{ trend.hashtag|clean_hashtag }}" target="_blank"><i class="fab fa-twitter    "></i> Ver en Twitter</a>
                                </div>
                            </li>
                        {% endfor %}
                    </ol>
                </div>
            </div>
        </div>
    </div>
        
{% endblock content %}

{% block title %}{{ hashtag }}{% endblock title %}

{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.0/moment.min.js" integrity="sha512-Izh34nqeeR7/nwthfeE0SI3c8uhFSnqxV0sI9TvTcXiFJkMd6fB644O64BRq2P/LA/+7eRvCw4GmLsXksyTHBg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.0/locale/es.min.js" integrity="sha512-L6Trpj0Q/FiqDMOD0FQ0dCzE0qYT2TFpxkIpXRSWlyPvaLNkGEMRuXoz6MC5PrtcbXtgDLAAI4VFtPvfYZXEtg==" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
<script>
    var nan = null;
    function getRandomColor() {
        var letters = '0123456789ABCDEF';
        var color = '#';
        for (var i = 0; i < 6; i++) {
            color += letters[Math.floor(Math.random() * 16)];
        }
        return color;
    }

    var l = function(d) {
        var entries = Object.entries(d);
        var labels = [];
        for(var item in entries) {
            if(item > 1) {
                if(entries[item][1] != nan)
                    labels.push(moment(entries[item][0]).format('L'))
            }
        }
        return labels;
    }
    var gd = function(d) {
        var entries = Object.entries(d);
        var data = [];
        for(var item in entries) {
            if(item > 1) {
                if(entries[item][1] != nan)
                    data.push(entries[item][1].toFixed(2))
            }
        }
        return data;
    }
</script>
<script>
    {% for n in newdf %}
    var color = getRandomColor()
    var ctx{{ forloop.counter0 }} = document.getElementById('chart{{ forloop.counter0 }}').getContext('2d');
    var it = {{n|safe}};
    var labels = l(it);
    var myLineChart{{ forloop.counter0 }} = new Chart(ctx{{ forloop.counter0 }}, {
        type: (labels.length > 1) ? 'line' : 'bar',
        data: {
            labels: labels,
            datasets: [{
                label: 'Promedio de Tweets',
                data: gd(it),
                backgroundColor: color + '44',
                borderColor: color,
            }]
            
        },
        options: {
            
        }
    });
    {% endfor %}
</script>
{% endblock js %}
    